# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 08:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='created',
        ),
        migrations.AddField(
            model_name='statement',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 10, 8, 1, 20, 89216, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statement',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='prenume'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='position',
            field=models.CharField(max_length=255, verbose_name='func\u021bie'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='position_location',
            field=models.CharField(max_length=255, verbose_name='locul func\u021biei'),
        ),
    ]
