# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 15:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_auto_20160810_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='position',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='position_location',
        ),
        migrations.AddField(
            model_name='statement',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'default': 'value'}),
            preserve_default=False,
        ),
    ]
