# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 08:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_auto_20160821_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestsStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Statement',
            new_name='WealthStatement',
        ),
    ]
